In [1]:
import pandas as pd
from pathlib import Path

In [2]:
raw_folder = Path("../data/raw")
processed_folder = Path("../data/processed")
processed_folder.mkdir(parents=True, exist_ok=True)

In [3]:
bank_files = {
    "CBA": "Commonwealth Bank of Australia.csv",
    "NAB": "National Australia Bank.csv",
    "WBC": "Westpac Banking Corporation.csv",
    "ANZ": "Australia and New Zealand Banking Group.csv",
    "MQG": "Macquarie Group Limited.csv",
}

In [4]:
banks = {}

for bank, filename in bank_files.items():

    file_path = raw_folder / filename

    df = pd.read_csv(file_path)

    banks[bank] = df

    print(bank, ":", df.shape[0], "rows loaded", sep="")

CBA:6349rows loaded
NAB:6349rows loaded
WBC:6349rows loaded
ANZ:6349rows loaded
MQG:6349rows loaded

In [5]:
from IPython.display import display

for bank, df in banks.items():

    print("\n" + "=" * 50)
    print(bank)
    print("=" * 50)

    display(df.head())

==================================================
CBA
==================================================

         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   8.296802  29.699089  30.037258  29.440491  29.730917  3071095
1  2001-07-31   8.196772  29.341030  29.738874  29.341030  29.689144  2660003
2  2001-08-01   8.438504  30.206343  30.206343  29.360922  29.390760  2969546
3  2001-08-02   8.477962  30.347576  30.862785  30.285910  30.285910  2791502
4  2001-08-03   8.299582  29.709036  30.236179  29.579737  30.236179  3593186

==================================================
NAB
==================================================

         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   7.551603  30.412500  30.678862  30.269810  30.269810  1657873
1  2001-07-31   7.650812  30.812040  30.916681  30.345913  30.457212  2790067
2  2001-08-01   7.865762  31.677708  31.706245  30.964245  30.975660  3280887
3  2001-08-02   7.960246  32.058220  32.248478  31.820400  31.880329  2771054
4  2001-08-03   7.983869  32.153347  32.191399  31.725271  31.861305  2876820

==================================================
WBC
==================================================

         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   3.621745  13.825873  13.845738  13.597428  13.607361  2519741
1  2001-07-31   3.567105  13.617293  13.875535  13.597428  13.855670  2191596
2  2001-08-01   3.637354  13.885467  13.895400  13.627225  13.696752  2679221
3  2001-08-02   3.681584  14.054318  14.084115  13.885467  13.905332  3171674
4  2001-08-03   3.709685  14.161587  14.262898  13.935129  13.935129  2342177

==================================================
ANZ
==================================================

         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   3.909603  15.051689  15.070646  14.805251  14.805251  1854685
1  2001-07-31   3.838204  14.776815  15.099081  14.776815  15.051689  1523686
2  2001-08-01   3.963766  15.260213  15.260213  14.833686  14.872547  3292374
3  2001-08-02   3.988384  15.354997  15.497173  15.269692  15.326562  2522939
4  2001-08-03   4.086864  15.734133  15.743612  15.317084  15.402389  3682953

==================================================
MQG
==================================================

         Date  Adj Close      Close       High        Low       Open  Volume
0  2001-07-30  11.551105  34.911732  35.059246  34.715046  34.780937  509268
1  2001-07-31  11.730391  35.453602  36.042675  34.976639  34.976639  333980
2  2001-08-01  11.486030  34.715046  35.600132  34.567532  35.594231  547922
3  2001-08-02  11.795137  35.649303  35.895161  34.439686  34.997292  768520
4  2001-08-03  11.827676  35.747646  35.895161  35.550961  35.600132  428403

In [6]:
for bank, df in banks.items():

    print("\n", bank)

    print(df.isnull().sum())

 CBA
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

 NAB
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

 WBC
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

 ANZ
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

 MQG
Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [7]:
for bank, df in banks.items():
    print(bank)
    print(df.head())
    print(df.columns)

CBA
         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   8.296802  29.699089  30.037258  29.440491  29.730917  3071095
1  2001-07-31   8.196772  29.341030  29.738874  29.341030  29.689144  2660003
2  2001-08-01   8.438504  30.206343  30.206343  29.360922  29.390760  2969546
3  2001-08-02   8.477962  30.347576  30.862785  30.285910  30.285910  2791502
4  2001-08-03   8.299582  29.709036  30.236179  29.579737  30.236179  3593186
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
NAB
         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   7.551603  30.412500  30.678862  30.269810  30.269810  1657873
1  2001-07-31   7.650812  30.812040  30.916681  30.345913  30.457212  2790067
2  2001-08-01   7.865762  31.677708  31.706245  30.964245  30.975660  3280887
3  2001-08-02   7.960246  32.058220  32.248478  31.820400  31.880329  2771054
4  2001-08-03   7.983869  32.153347  32.191399  31.725271  31.861305  2876820
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
WBC
         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   3.621745  13.825873  13.845738  13.597428  13.607361  2519741
1  2001-07-31   3.567105  13.617293  13.875535  13.597428  13.855670  2191596
2  2001-08-01   3.637354  13.885467  13.895400  13.627225  13.696752  2679221
3  2001-08-02   3.681584  14.054318  14.084115  13.885467  13.905332  3171674
4  2001-08-03   3.709685  14.161587  14.262898  13.935129  13.935129  2342177
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
ANZ
         Date  Adj Close      Close       High        Low       Open   Volume
0  2001-07-30   3.909603  15.051689  15.070646  14.805251  14.805251  1854685
1  2001-07-31   3.838204  14.776815  15.099081  14.776815  15.051689  1523686
2  2001-08-01   3.963766  15.260213  15.260213  14.833686  14.872547  3292374
3  2001-08-02   3.988384  15.354997  15.497173  15.269692  15.326562  2522939
4  2001-08-03   4.086864  15.734133  15.743612  15.317084  15.402389  3682953
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')
MQG
         Date  Adj Close      Close       High        Low       Open  Volume
0  2001-07-30  11.551105  34.911732  35.059246  34.715046  34.780937  509268
1  2001-07-31  11.730391  35.453602  36.042675  34.976639  34.976639  333980
2  2001-08-01  11.486030  34.715046  35.600132  34.567532  35.594231  547922
3  2001-08-02  11.795137  35.649303  35.895161  34.439686  34.997292  768520
4  2001-08-03  11.827676  35.747646  35.895161  35.550961  35.600132  428403
Index(['Date', 'Adj Close', 'Close', 'High', 'Low', 'Open', 'Volume'], dtype='str')

In [8]:
for bank, df in banks.items():

    df["Date"] = pd.to_datetime(df["Date"])

    banks[bank] = df

In [9]:
for bank, df in banks.items():

    duplicates = df["Date"].duplicated().sum()

    print(bank, ":", duplicates, "duplicate dates")

CBA : 0 duplicate dates
NAB : 0 duplicate dates
WBC : 0 duplicate dates
ANZ : 0 duplicate dates
MQG : 0 duplicate dates

In [10]:
for bank, df in banks.items():

    df = df.sort_values("Date")

    banks[bank] = df

In [11]:

for bank, df in banks.items():
    df.to_csv(
        processed_folder / f"{bank}_clean.csv",
        index=False
    )
print("Cleaned bank files saved successfully.")

Cleaned bank files saved successfully.

In [12]:
returns = pd.DataFrame()
for bank, df in banks.items():
    returns[bank] = df['Adj Close'].pct_change()

returns = returns.dropna()

In [13]:
import numpy as np
log_returns = np.log(1 + returns)

In [14]:
log_returns.to_csv('../data/processed/daily_log_returns.csv')